name: Debian Package Build

on:
  push:
    #branches: [ master, main ]
    branches: ["*"]
    tags: [ 'v*' ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  build-debian:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - arch: amd64
            platform: linux/amd64
            ghc_ver: 9.6.7
            os: ubuntu-latest
          - arch: arm64
            platform: linux/arm64
            ghc_ver: 9.6.7
            os: ubuntu-24.04-arm
          #- arch: i386
          #  platform: linux/386
          #  ghc_ver: 8.10.7
    env:
      CABAL_VER: 3.14.1.1
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      
      - name: Set up QEMU for ${{ matrix.arch }}
        uses: docker/setup-qemu-action@v3
        with:
          platforms: ${{ matrix.platform }}
      
      - name: Setup dependecies
        run: |
          sudo apt-get update
          # sudo apt-get install -y --no-install-recommends \
          sudo apt-get install -y \
            build-essential \
            debhelper-compat \
            devscripts \
            pkgconf \
            curl \
            ca-certificates \
            libffi-dev \
            libgmp-dev \
            libncurses-dev \
            zlib1g-dev \
            libssl-dev \
            liblzma-dev \
            libbz2-dev
            
          curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org \
            | BOOTSTRAP_HASKELL_NONINTERACTIVE=1 sh

      - name: Build Debian package
        run: |
          # alternatively we could also build the debian package in a docker container to have a more clean environment and avoid installing all the dependencies on the runner but for now we are installing them directly on the runner to get it rolling
          # docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace --platform ${{ matrix.platform }} \
          # bash -c "cd debian && debuild -b"
          
          # Build the Debian package without signing 
          # TODO: Add -uc -us (unsigned source and usigned changes and later sign them) 
          # for know we are only building the binary package to get it rolling
          debuild -b 

          mkdir -p /out
          #mv ../*.deb /out/ghcup-${{ matrix.arch }}.deb
          mv ../*.deb /out/
          mv ../*.changes /out/


      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ghcup-${{ matrix.arch }}
          path: |
            /out/*.deb 
            /out/*.changes

  #release:
  #  name: release
  #  needs: ["test-linux", "test-arm", "test-macwin", "test-freebsd", "hls"]
  #  runs-on: ubuntu-latest
  #  if: startsWith(github.ref, 'refs/tags/v')
  #  steps:
  #    - name: Download artifacts
  #      uses: actions/download-artifact@v4
  #      with:
  #        pattern: artifacts-*
  #        merge-multiple: true
  #        path: ./out
  #
  #    - name: Release
  #      uses: softprops/action-gh-release@v1
  #      with:
  #        draft: true
  #        files: |
  #          ./out/*
  #